# -*- coding: utf-8 -*-
"""
The Xiaomi Home integration Init File.
"""
import logging
from typing import Optional

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant, callback
from homeassistant.components import persistent_notification
from homeassistant.helpers import device_registry, entity_registry
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.util import slugify
import re

from .miot.common import slugify_did, MIoTHttp
from .miot.miot_storage import (
    DeviceManufacturer, MIoTStorage, MIoTCert)
from .miot.miot_spec import (
    MIoTSpecInstance, MIoTSpecParser, MIoTSpecService)
from .miot.const import (
    DEFAULT_INTEGRATION_LANGUAGE, DOMAIN, SUPPORTED_PLATFORMS)
from .miot.miot_error import MIoTOauthError
from .miot.miot_device import MIoTDevice
from .miot.miot_client import MIoTClient, get_miot_instance_async

_LOGGER = logging.getLogger(__name__)


async def async_setup(hass: HomeAssistant, hass_config: dict) -> bool:
    # pylint: disable=unused-argument
    hass.data.setdefault(DOMAIN, {})
    # {[entry_id:str]: MIoTClient}, miot client instance
    hass.data[DOMAIN].setdefault('miot_clients', {})
    hass.data[DOMAIN].setdefault('devices', {})
    MIoTHttp.set_shared_session(async_get_clientsession(hass))
    return True


async def _async_migrate_legacy_entity_ids(hass: HomeAssistant, entry_id: str, miot_devices: list[MIoTDevice]) -> None:
    """Migrate entity IDs to the stable {did}_{model}_{feature} format."""
    er = entity_registry.async_get(hass)
    
    # Build a map of unique_id -> target entity_id
    expected_ids_map = {}
    main_entity_uids = {}
    for device in miot_devices:
        expected_ids_map.update(device.get_expected_entity_ids())
        # Add custom diagnostic sensors to migration map
        uid_control = f"{entry_id}_{device.did}_control_path"
        uid_ip = f"{entry_id}_{device.did}_ip_address"
        expected_ids_map[uid_control] = f"sensor.{device.entity_id_prefix}_control_path"
        expected_ids_map[uid_ip] = f"sensor.{device.entity_id_prefix}_ip_address"
        
        main_entity_uids[device.gen_device_unique_id()] = device.entity_id_prefix

    # --- Phase 1: Remove legacy action entity orphans ---
    # In the original Xiaomi code, MIoTActionEntity used unique_id = entity_id (name-based).
    # Since r17 we use gen_action_unique_id (DID-based). The old entries can't be matched by
    # the new unique_id, so they become orphans while new correctly-named entities are created
    # alongside them. Clean up those orphans first so there's no conflict.
    ACTION_DOMAINS = {'notify', 'button'}
    entries_snapshot = list(entity_registry.async_entries_for_config_entry(er, entry_id))
    for entry in entries_snapshot:
        if entry.domain in ACTION_DOMAINS and entry.unique_id == entry.entity_id:
            # Old format: unique_id == entity_id (name-based). Remove so platform can
            # freshly register with stable DID-based entity_id + new unique_id.
            try:
                er.async_remove(entry.entity_id)
                _LOGGER.info(
                    "Removed legacy action entity orphan %s (old unique_id==entity_id format)",
                    entry.entity_id,
                )
            except Exception as err:  # pylint: disable=broad-exception-caught
                _LOGGER.warning(
                    "Failed to remove legacy action entity %s: %s",
                    entry.entity_id, err,
                )

    # --- Phase 2: Migrate remaining entities to stable entity_id format ---
    for entry in entity_registry.async_entries_for_config_entry(er, entry_id):
        new_entity_id = None
        
        # Legacy unique_ids had the domain prefix (e.g. binary_sensor.xiaomi_cn_blt_...)
        # The new format generated by gen_prop_unique_id does not.
        match_id = entry.unique_id
        if match_id not in expected_ids_map and match_id.startswith(f"{entry.domain}."):
            match_id = match_id.split('.', 1)[1]
            
        if match_id in expected_ids_map:
            target_id = expected_ids_map[match_id]
            if target_id == "unknown":
                # Main entity
                prefix = main_entity_uids.get(match_id)
                if prefix:
                    new_entity_id = f"{entry.domain}.{prefix}"
            else:
                # Sub entity
                new_entity_id = target_id
                # Fix domain if necessary (e.g. sometimes it gets overridden)
                if new_entity_id and new_entity_id.split('.')[0] != entry.domain:
                    new_entity_id = f"{entry.domain}.{new_entity_id.split('.', 1)[1]}"
                    
        if new_entity_id and new_entity_id != entry.entity_id:
            try:
                er.async_update_entity(entry.entity_id, new_entity_id=new_entity_id)
                _LOGGER.info(
                    "Migrated entity %s to modern stable format %s", 
                    entry.entity_id, new_entity_id
                )
            except ValueError as err:
                _LOGGER.warning(
                    "Failed to migrate entity %s to %s: %s", 
                    entry.entity_id, new_entity_id, err
                )


def _async_cleanup_entity_registry(hass: HomeAssistant, entry_id: str) -> None:
    """Clean up invalid entities from the entity registry."""
    er = entity_registry.async_get(hass=hass)
    entries_to_remove = entity_registry.async_entries_for_config_entry(er, entry_id)
    if not isinstance(entries_to_remove, list):
        entries_to_remove = list(entries_to_remove)

    for entry in entries_to_remove:
        if (
            entry.entity_id.startswith(f'{DOMAIN}.')
            or entry.entity_id.split('.', 1)[0] not in SUPPORTED_PLATFORMS
        ):
            er.async_remove(entity_id=entry.entity_id)


async def _async_remove_deleted_devices(
    hass: HomeAssistant,
    entry_data: dict,
    miot_client: MIoTClient,
) -> None:
    """Remove deleted devices from HA device registry."""
    devices_remove = (await miot_client.miot_storage.load_user_config_async(
        uid=entry_data['uid'],
        cloud_server=entry_data['cloud_server'],
        keys=['devices_remove'])).get('devices_remove', [])

    if isinstance(devices_remove, list) and devices_remove:
        dr = device_registry.async_get(hass)
        for did in devices_remove:
            device_entry = dr.async_get_device(
                identifiers={(
                    DOMAIN,
                    slugify_did(
                        cloud_server=entry_data['cloud_server'],
                        did=did))},
                connections=None)
            if not device_entry:
                _LOGGER.error('remove device not found, %s', did)
                continue
            dr.async_remove_device(device_id=device_entry.id)
            _LOGGER.info(
                'delete device entry, %s, %s', did, device_entry.id)
        await miot_client.miot_storage.update_user_config_async(
            uid=entry_data['uid'],
            cloud_server=entry_data['cloud_server'],
            config={'devices_remove': []})


async def async_setup_entry(
    hass: HomeAssistant, config_entry: ConfigEntry
) -> bool:
    """Set up an entry."""
    def ha_persistent_notify(
        notify_id: str, title: Optional[str] = None,
        message: Optional[str] = None
    ) -> None:
        """Send messages in Notifications dialog box."""
        if title:
            persistent_notification.async_create(
                hass=hass,  message=message or '',
                title=title, notification_id=notify_id)
        else:
            persistent_notification.async_dismiss(
                hass=hass, notification_id=notify_id)

    entry_id = config_entry.entry_id
    entry_data = dict(config_entry.data)

    ha_persistent_notify(
        notify_id=f'{entry_id}.oauth_error', title=None, message=None)

    try:
        miot_client: MIoTClient = await get_miot_instance_async(
            hass=hass, entry_id=entry_id,
            entry_data=entry_data,
            persistent_notify=ha_persistent_notify)
        # Spec parser
        spec_parser = MIoTSpecParser(
            lang=entry_data.get(
                'integration_language', DEFAULT_INTEGRATION_LANGUAGE),
            storage=miot_client.miot_storage,
            loop=miot_client.main_loop
        )
        await spec_parser.init_async()
        # Manufacturer
        manufacturer: DeviceManufacturer = DeviceManufacturer(
            storage=miot_client.miot_storage,
            loop=miot_client.main_loop)
        await manufacturer.init_async()
        miot_devices: list[MIoTDevice] = []
        _async_cleanup_entity_registry(hass, entry_id)
        er = entity_registry.async_get(hass=hass)
        er_entries = list(entity_registry.async_entries_for_config_entry(er, entry_id))
        
        # Remove entities from HA entity registry
        def _remove_from_registry_by_uid(unique_ids: list[str]) -> None:
            for uid in unique_ids:
                for entry in er_entries:
                    match_id = entry.unique_id
                    if match_id != uid and match_id.startswith(f"{entry.domain}."):
                        match_id = match_id.split('.', 1)[1]
                        
                    if match_id == uid:
                        er.async_remove(entry.entity_id)
                        er_entries.remove(entry)
                        break

        for did, info in miot_client.device_list.items():
            spec_instance = await spec_parser.parse(urn=info['urn'])
            if not isinstance(spec_instance, MIoTSpecInstance):
                _LOGGER.error('spec content is None, %s, %s', did, info)
                continue
            device: MIoTDevice = MIoTDevice(
                miot_client=miot_client,
                device_info={
                    **info, 'manufacturer': manufacturer.get_name(
                        info.get('manufacturer', ''))},
                spec_instance=spec_instance)
            miot_devices.append(device)
            device.spec_transform()
            
            # Remove filter entities and non-standard entities using helper function
            def _filter_platform(platform_dict: dict, item_type: str, uid_gen_func, has_description=False):
                if platform not in platform_dict:
                    return
                kept_items = []
                for item in platform_dict[platform]:
                    spec_item = item.spec if item_type == 'service' else item
                    if (item_type == 'service' and not isinstance(spec_item, MIoTSpecService)):
                        kept_items.append(item)
                        continue
                    if spec_item.need_filter or (miot_client.hide_non_standard_entities and spec_item.proprietary):
                        uids_to_remove = []
                        if has_description:
                            uids_to_remove.append(uid_gen_func(siid=spec_item.iid, description=spec_item.description, slugify_description=False))
                            uids_to_remove.append(uid_gen_func(siid=spec_item.iid, description=spec_item.description))
                        elif item_type == 'property':
                            uids_to_remove.append(uid_gen_func(spec_name=spec_item.name, siid=spec_item.service.iid, piid=spec_item.iid))
                        elif item_type == 'event':
                            uids_to_remove.append(uid_gen_func(spec_name=spec_item.name, siid=spec_item.service.iid, eiid=spec_item.iid))
                        elif item_type == 'action':
                            uids_to_remove.append(uid_gen_func(spec_name=spec_item.name, siid=spec_item.service.iid, aiid=spec_item.iid))
                        _remove_from_registry_by_uid(uids_to_remove)
                    else:
                        kept_items.append(item)
                platform_dict[platform] = kept_items

            for platform in SUPPORTED_PLATFORMS:
                _filter_platform(device.entity_list, 'service', device.gen_service_unique_id, True)
                _filter_platform(device.prop_list, 'property', device.gen_prop_unique_id, False)
                _filter_platform(device.event_list, 'event', device.gen_event_unique_id, False)
                _filter_platform(device.action_list, 'action', device.gen_action_unique_id, False)

            # Action debug
            if not miot_client.action_debug:
                uids_to_remove = []
                for action in device.action_list.get('notify', []):
                    uids_to_remove.append(device.gen_action_unique_id(spec_name=action.name, siid=action.service.iid, aiid=action.iid))
                _remove_from_registry_by_uid(uids_to_remove)
                device.action_list['notify'] = []
                    
            # Binary sensor display
            if not miot_client.display_binary_bool:
                for prop in device.prop_list.get('binary_sensor', []):
                    _remove_from_registry_by_uid([
                        device.gen_prop_unique_id(spec_name=prop.name, siid=prop.service.iid, piid=prop.iid)
                    ])
            if not miot_client.display_binary_text:
                for prop in device.prop_list.get('binary_sensor', []):
                    _remove_from_registry_by_uid([
                        device.gen_prop_unique_id(spec_name=prop.name, siid=prop.service.iid, piid=prop.iid)
                    ])

        hass.data[DOMAIN]['devices'][entry_id] = miot_devices
        
        # Pre-register devices in the device registry.
        # This prevents a race condition where HA generates entity_ids for sub-entities
        # before the device is fully registered, causing it to fall back to unique_id.
        dr = device_registry.async_get(hass)
        for device in miot_devices:
            if device.device_info:
                dr.async_get_or_create(
                    config_entry_id=entry_id,
                    **device.device_info
                )
                
        # Register a migration script to fix any existing fallback entity_ids
        # generated in previous sessions due to the race condition, and migrate to the new format.
        await _async_migrate_legacy_entity_ids(hass, entry_id, miot_devices)

        await hass.config_entries.async_forward_entry_setups(
            config_entry, SUPPORTED_PLATFORMS)

        # Remove the deleted devices
        await _async_remove_deleted_devices(hass, entry_data, miot_client)

        await spec_parser.deinit_async()
        await manufacturer.deinit_async()

    except MIoTOauthError as oauth_error:
        ha_persistent_notify(
            notify_id=f'{entry_id}.oauth_error',
            title='Xiaomi Home Oauth Error',
            message=f'Please re-add.\r\nerror: {oauth_error}'
        )
    except Exception as err:
        miot_client: MIoTClient = hass.data[DOMAIN].get('miot_clients', {}).pop(
            entry_id, None)
        if miot_client:
            await miot_client.deinit_async()
        raise err

    return True


async def async_unload_entry(
    hass: HomeAssistant, config_entry: ConfigEntry
) -> bool:
    """Unload the entry."""
    entry_id = config_entry.entry_id
    # Unload the platform
    unload_ok = await hass.config_entries.async_unload_platforms(
        config_entry, SUPPORTED_PLATFORMS)
    if unload_ok:
        hass.data[DOMAIN]['devices'].pop(entry_id, None)
    # Remove integration data
    miot_client: MIoTClient = hass.data[DOMAIN]['miot_clients'].pop(
        entry_id, None)
    if miot_client:
        await miot_client.deinit_async()
    del miot_client
    return True


async def async_remove_entry(
    hass: HomeAssistant, config_entry: ConfigEntry
) -> bool:
    """Remove the entry."""
    entry_data = dict(config_entry.data)
    uid: str = entry_data['uid']
    cloud_server: str = entry_data['cloud_server']
    miot_storage: MIoTStorage = hass.data[DOMAIN]['miot_storage']
    miot_cert: MIoTCert = MIoTCert(
        storage=miot_storage, uid=uid, cloud_server=cloud_server)

    # Clean device list
    await miot_storage.remove_async(
        domain='miot_devices', name=f'{uid}_{cloud_server}', type_=dict)
    # Clean user configuration
    await miot_storage.update_user_config_async(
        uid=uid, cloud_server=cloud_server, config=None)
    # Clean cert file
    await miot_cert.remove_user_cert_async()
    await miot_cert.remove_user_key_async()
    return True


async def async_remove_config_entry_device(
    hass: HomeAssistant,
    config_entry: ConfigEntry,
    device_entry: device_registry.DeviceEntry
) -> bool:
    """Remove the device."""
    miot_client: MIoTClient = await get_miot_instance_async(
        hass=hass, entry_id=config_entry.entry_id)

    if len(device_entry.identifiers) != 1:
        _LOGGER.error(
            'remove device failed, invalid identifiers, %s, %s',
            device_entry.id, device_entry.identifiers)
        return False
    identifiers = list(device_entry.identifiers)[0]
    if identifiers[0] != DOMAIN:
        _LOGGER.error(
            'remove device failed, invalid domain, %s, %s',
            device_entry.id, device_entry.identifiers)
        return False

    # Remove device
    await miot_client.remove_device2_async(did_tag=identifiers[1])
    device_registry.async_get(hass).async_remove_device(device_entry.id)
    _LOGGER.info(
        'remove device, %s, %s', identifiers[1], device_entry.id)
    return True
